# Generated by Django 3.2.6 on 2021-11-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(default='Santo Antonio', max_length=60),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(default='Vicosa', max_length=60),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(default='Rua Mariquinha Maciel', max_length=60),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo')], default='MG', max_length=9),
        ),
    ]
