# Generated by Django 3.2.6 on 2021-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211106_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(default='305/201', max_length=8),
        ),
    ]
