# Generated by Django 3.2.6 on 2021-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='codfunc',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='codfunc'),
        ),
    ]
