# Generated by Django 3.2.6 on 2021-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211108_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='31', max_length=13),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapa'), ('BA', 'Bahia'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('PR', 'Paraná'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='MG', max_length=9),
        ),
    ]
