# Generated by Django 3.2.6 on 2021-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211111_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(max_length=20),
        ),
    ]
